version: '3.8'
services:
  content_provider:
    image: oat431/content:latest
    ports:
      - 5000:5000
  backend:
    image: oat431/admin:latest
    ports:
      - 8080:8080
  frontend:
    image: oat431/platform:latest
    ports:
      - 80:80