version: '3.8'
services:
  content_provider:
    image: oat431/content:latest
    ports:
      - 5000:5000
  backend:
    image: oat431/admin:test
    ports:
      - 3917:3917
  frontend:
    image: oat431/platform:test
    ports:
      - 3300:80